name: 24ds3000008@ds.study.iitm.ac.in 

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 24ds3000008@ds.study.iitm.ac.in
        run: echo \"Hello from email step!\"
